[2024-11-15T21:46:21.618+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-15T21:46:21.711+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_sentiment_testinggg.process_data scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2024-11-15T21:46:21.745+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_sentiment_testinggg.process_data scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2024-11-15T21:46:21.753+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-15T21:46:21.959+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_data> on 2023-10-02 00:00:00+00:00
[2024-11-15T21:46:22.025+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=532) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-15T21:46:22.037+0000] {standard_task_runner.py:72} INFO - Started process 585 to run task
[2024-11-15T21:46:22.058+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stock_sentiment_testinggg', 'process_data', 'scheduled__2023-10-02T00:00:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/ETL_saham_test.py', '--cfg-path', '/tmp/tmpq44sax27']
[2024-11-15T21:46:22.068+0000] {standard_task_runner.py:105} INFO - Job 60: Subtask process_data
[2024-11-15T21:46:22.365+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_sentiment_testinggg.process_data scheduled__2023-10-02T00:00:00+00:00 [running]> on host 50375b572a3b
[2024-11-15T21:46:22.927+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_sentiment_testinggg' AIRFLOW_CTX_TASK_ID='process_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-02T00:00:00+00:00'
[2024-11-15T21:46:22.931+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-15T21:46:22.932+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-15T21:46:22.934+0000] {logging_mixin.py:190} INFO - Current task name:process_data state:running start_date:2024-11-15 21:46:21.713902+00:00
[2024-11-15T21:46:22.940+0000] {logging_mixin.py:190} INFO - Dag name:stock_sentiment_testinggg and current dag run status:running
[2024-11-15T21:46:22.954+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-15T21:46:23.022+0000] {logging_mixin.py:190} INFO - Kunci 'Time Series (Daily)' tidak ditemukan dalam data JSON.
[2024-11-15T21:46:24.132+0000] {log.py:232} WARNING - [nltk_data] Downloading package vader_lexicon to
[nltk_data]     /home/***/nltk_data...
[2024-11-15T21:46:24.149+0000] {log.py:232} WARNING - [nltk_data]   Package vader_lexicon is already up-to-date!
[2024-11-15T21:46:24.189+0000] {logging_mixin.py:190} INFO - Kolom yang diperlukan tidak ditemukan dalam data berita.
[2024-11-15T21:46:24.293+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-15T21:46:24.377+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-15T21:46:24.379+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=stock_sentiment_testinggg, task_id=process_data, run_id=scheduled__2023-10-02T00:00:00+00:00, execution_date=20231002T000000, start_date=20241115T214621, end_date=20241115T214624
[2024-11-15T21:46:24.839+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-15T21:46:24.843+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-15T21:46:24.845+0000] {logging_mixin.py:190} INFO - Dag name:stock_sentiment_testinggg queued_at:2024-11-15 21:45:43.014992+00:00
[2024-11-15T21:46:24.846+0000] {logging_mixin.py:190} INFO - Task hostname:50375b572a3b operator:PythonOperator
[2024-11-15T21:46:24.975+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-15T21:46:25.134+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-15T21:46:25.169+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-15T22:02:11.170+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-15T22:02:11.418+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_sentiment_testinggg.process_data scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2024-11-15T22:02:11.488+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_sentiment_testinggg.process_data scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2024-11-15T22:02:11.519+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-15T22:02:11.672+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_data> on 2023-10-02 00:00:00+00:00
[2024-11-15T22:02:11.744+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1387) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-15T22:02:11.768+0000] {standard_task_runner.py:72} INFO - Started process 1432 to run task
[2024-11-15T22:02:11.752+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stock_sentiment_testinggg', 'process_data', 'scheduled__2023-10-02T00:00:00+00:00', '--job-id', '223', '--raw', '--subdir', 'DAGS_FOLDER/ETL_saham_test.py', '--cfg-path', '/tmp/tmpyf4ywfd0']
[2024-11-15T22:02:11.808+0000] {standard_task_runner.py:105} INFO - Job 223: Subtask process_data
[2024-11-15T22:02:12.118+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_sentiment_testinggg.process_data scheduled__2023-10-02T00:00:00+00:00 [running]> on host 50375b572a3b
[2024-11-15T22:02:12.791+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_sentiment_testinggg' AIRFLOW_CTX_TASK_ID='process_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-02T00:00:00+00:00'
[2024-11-15T22:02:12.810+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-15T22:02:12.815+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-15T22:02:12.832+0000] {logging_mixin.py:190} INFO - Current task name:process_data state:running start_date:2024-11-15 22:02:11.440805+00:00
[2024-11-15T22:02:12.836+0000] {logging_mixin.py:190} INFO - Dag name:stock_sentiment_testinggg and current dag run status:running
[2024-11-15T22:02:12.843+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-15T22:02:12.913+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ETL_saham_test.py", line 68, in process_data
    df_stock = process_stock_data(data_stock)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ETL_saham_test.py", line 81, in process_stock_data
    df_stock = pd.DataFrame.from_dict(data_stock['Time Series (Daily)'], orient='index')
                                      ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-11-15T22:02:13.024+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-15T22:02:13.025+0000] {logging_mixin.py:190} INFO - Task start:2024-11-15 22:02:11.440805+00:00 end:2024-11-15 22:02:13.022794+00:00 duration:1.581989
[2024-11-15T22:02:13.027+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): process_data> dag:<DAG: stock_sentiment_testinggg> dagrun:<DagRun stock_sentiment_testinggg @ 2023-10-02 00:00:00+00:00: scheduled__2023-10-02T00:00:00+00:00, state:running, queued_at: 2024-11-15 22:01:33.811596+00:00. externally triggered: False>
[2024-11-15T22:02:13.028+0000] {logging_mixin.py:190} INFO - Failure caused by 'NoneType' object is not subscriptable
[2024-11-15T22:02:13.030+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_sentiment_testinggg, task_id=process_data, run_id=scheduled__2023-10-02T00:00:00+00:00, execution_date=20231002T000000, start_date=20241115T220211, end_date=20241115T220213
[2024-11-15T22:02:13.132+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-15T22:02:13.136+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 223 for task process_data ('NoneType' object is not subscriptable; 1432)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ETL_saham_test.py", line 68, in process_data
    df_stock = process_stock_data(data_stock)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ETL_saham_test.py", line 81, in process_stock_data
    df_stock = pd.DataFrame.from_dict(data_stock['Time Series (Daily)'], orient='index')
                                      ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-11-15T22:02:13.280+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-15T22:02:13.402+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-15T22:02:13.414+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
